<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "megafry_template"
 *
 * Auto generated by Extension Builder 2017-01-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Megafry Template',
	'description' => 'The template ext',
	'category' => 'misc',
	'author' => 'Eugen',
	'author_email' => 'eugene.fritz@hotmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'ws_less' => '',
			'gridelements' => '',
			'cdsrc_baseurl' => '',

		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
